package com.trixxexe.trixxwave.media

import android.content.ContentUris
import android.content.Context
import android.media.MediaMetadataRetriever
import android.net.Uri
import android.os.Build
import android.provider.MediaStore
import com.trixxexe.trixxwave.data.db.Playlist
import com.trixxexe.trixxwave.data.db.Song
import com.trixxexe.trixxwave.data.db.TrixxWaveDatabase
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.firstOrNull
import kotlinx.coroutines.withContext
import java.io.File

object MediaStoreScanner {

    suspend fun scanDeviceAudio(context: Context): Int = withContext(Dispatchers.IO) {
        val database = TrixxWaveDatabase.getDatabase(context)
        val songDao = database.songDao()
        val playlistDao = database.playlistDao()

        val collection = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            MediaStore.Audio.Media.getContentUri(MediaStore.VOLUME_EXTERNAL)
        } else {
            MediaStore.Audio.Media.EXTERNAL_CONTENT_URI
        }

        val projection = arrayOf(
            MediaStore.Audio.Media._ID,
            MediaStore.Audio.Media.TITLE,
            MediaStore.Audio.Media.ARTIST,
            MediaStore.Audio.Media.ALBUM,
            MediaStore.Audio.Media.DURATION,
            MediaStore.Audio.Media.DATA,
            MediaStore.Audio.Media.ALBUM_ID
        )

        val selection = "${MediaStore.Audio.Media.IS_MUSIC} != 0"
        val sortOrder = "${MediaStore.Audio.Media.DATE_ADDED} DESC"

        var addedCount = 0

        try {
            context.contentResolver.query(
                collection,
                projection,
                selection,
                null,
                sortOrder
            )?.use { cursor ->
                val idColumn = cursor.getColumnIndexOrThrow(MediaStore.Audio.Media._ID)
                val titleColumn = cursor.getColumnIndexOrThrow(MediaStore.Audio.Media.TITLE)
                val artistColumn = cursor.getColumnIndexOrThrow(MediaStore.Audio.Media.ARTIST)
                val albumColumn = cursor.getColumnIndexOrThrow(MediaStore.Audio.Media.ALBUM)
                val durationColumn = cursor.getColumnIndexOrThrow(MediaStore.Audio.Media.DURATION)
                val dataColumn = cursor.getColumnIndexOrThrow(MediaStore.Audio.Media.DATA)
                val albumIdColumn = cursor.getColumnIndexOrThrow(MediaStore.Audio.Media.ALBUM_ID)

                while (cursor.moveToNext()) {
                    val filePath = cursor.getString(dataColumn) ?: continue
                    if (songDao.getSongByPath(filePath) != null) continue

                    val mediaId = cursor.getLong(idColumn)
                    val title = cursor.getString(titleColumn) ?: File(filePath).nameWithoutExtension
                    val artist = cursor.getString(artistColumn).let {
                        if (it == null || it == "<unknown>") "Unknown Artist" else it
                    }
                    val album = cursor.getString(albumColumn).let {
                        if (it == null || it == "<unknown>") "Unknown Album" else it
                    }
                    val duration = cursor.getLong(durationColumn)
                    val albumId = cursor.getLong(albumIdColumn)

                    val albumArtUri = try {
                        val sArtworkUri = Uri.parse("content://media/external/audio/albumart")
                        ContentUris.withAppendedId(sArtworkUri, albumId).toString()
                    } catch (e: Exception) {
                        null
                    }

                    val waveform = WaveformExtractor.extractWaveformPoints(filePath)

                    val song = Song(
                        title = title,
                        artist = artist,
                        album = album,
                        durationMs = duration,
                        filePath = filePath,
                        albumArtUri = albumArtUri,
                        waveformPoints = waveform,
                        dateAdded = System.currentTimeMillis()
                    )
                    songDao.insertSong(song)
                    addedCount++
                }
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }

        // Initialize default smart playlists if none exist
        ensureDefaultPlaylists(playlistDao)

        addedCount
    }

    private suspend fun ensureDefaultPlaylists(playlistDao: com.trixxexe.trixxwave.data.db.PlaylistDao) {
        val existing = playlistDao.getAllPlaylists().firstOrNull()
        if (!existing.isNullOrEmpty()) return
        // If empty, insert standard playlists
        val defaultLists = listOf(
            Playlist(name = "Liked Songs", isAutoGenerated = true, description = "Your favorite tracks"),
            Playlist(name = "Cyberpunk Glass Mix", isAutoGenerated = true, description = "AI Curated Synth & Electro Wave"),
            Playlist(name = "Chill Ambient Flow", isAutoGenerated = true, description = "Relaxing acoustic & lofi melodies"),
            Playlist(name = "Midnight Focus Drive", isAutoGenerated = true, description = "High energy deep bass tracks")
        )
        for (pl in defaultLists) {
            playlistDao.insertPlaylist(pl)
        }
    }

    suspend fun importSingleFileUri(context: Context, uri: Uri): Song? = withContext(Dispatchers.IO) {
        val database = TrixxWaveDatabase.getDatabase(context)
        val songDao = database.songDao()

        val retriever = MediaMetadataRetriever()
        try {
            retriever.setDataSource(context, uri)
            val title = retriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_TITLE) ?: "Imported Track"
            val artist = retriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_ARTIST) ?: "Unknown Artist"
            val album = retriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_ALBUM) ?: "Imported Album"
            val durationStr = retriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION)
            val duration = durationStr?.toLongOrNull() ?: 180000L

            val filePath = uri.toString()
            val existing = songDao.getSongByPath(filePath)
            if (existing != null) return@withContext existing

            val waveform = WaveformExtractor.extractWaveformPoints(filePath)

            val song = Song(
                title = title,
                artist = artist,
                album = album,
                durationMs = duration,
                filePath = filePath,
                waveformPoints = waveform,
                dateAdded = System.currentTimeMillis()
            )
            val newId = songDao.insertSong(song)
            songDao.getSongById(newId)
        } catch (e: Exception) {
            null
        } finally {
            try { retriever.release() } catch (e: Exception) {}
        }
    }
}
