package com.trixxexe.trixxwave.data.db

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

@Entity(tableName = "songs")
data class Song(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val title: String,
    val artist: String = "Unknown Artist",
    val album: String = "Unknown Album",
    val durationMs: Long = 0L,
    val filePath: String,
    val albumArtUri: String? = null,
    val dateAdded: Long = System.currentTimeMillis(),
    val playCount: Int = 0,
    val isLiked: Boolean = false,
    val moodTags: String? = null,
    val waveformPoints: String? = null, // Cached amplitude array e.g. "20,45,80,60,30,90..."
    val genre: String? = null,
    val trimStartMs: Long = 0L,
    val trimEndMs: Long = 0L,
    val isGaplessAnalyzed: Boolean = false,
    val source: String = "LOCAL",
    val streamUrl: String? = null,
    val originalUrl: String? = null
)

@Entity(tableName = "albums")
data class Album(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val title: String,
    val artist: String = "Unknown Artist",
    val artUri: String? = null,
    val songCount: Int = 0
)

@Entity(tableName = "artists")
data class Artist(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val imageUri: String? = null,
    val songCount: Int = 0
)

@Entity(tableName = "playlists")
data class Playlist(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val coverUri: String? = null,
    val createdAt: Long = System.currentTimeMillis(),
    val isAutoGenerated: Boolean = false,
    val description: String? = null
)

@Entity(
    tableName = "playlist_song_cross_ref",
    primaryKeys = ["playlistId", "songId"],
    indices = [Index(value = ["playlistId"]), Index(value = ["songId"])],
    foreignKeys = [
        ForeignKey(
            entity = Playlist::class,
            parentColumns = ["id"],
            childColumns = ["playlistId"],
            onDelete = ForeignKey.CASCADE
        ),
        ForeignKey(
            entity = Song::class,
            parentColumns = ["id"],
            childColumns = ["songId"],
            onDelete = ForeignKey.CASCADE
        )
    ]
)
data class PlaylistSongCrossRef(
    val playlistId: Long,
    val songId: Long,
    val position: Int = 0
)

@Entity(tableName = "profiles")
data class Profile(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val avatarUri: String? = null,
    val pinHash: String? = null,
    val themePreset: String = "Frosted",
    val isActive: Boolean = false,
    val createdAt: Long = System.currentTimeMillis()
)

@Entity(
    tableName = "play_history",
    foreignKeys = [
        ForeignKey(
            entity = Song::class,
            parentColumns = ["id"],
            childColumns = ["songId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index(value = ["songId"])]
)
data class PlayHistoryEntry(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val songId: Long,
    val timestamp: Long = System.currentTimeMillis()
)

@Entity(tableName = "lyrics_cache")
data class LyricsCache(
    @PrimaryKey val songId: Long,
    val plainLyrics: String? = null,
    val syncedLrc: String? = null,
    val aiInsight: String? = null,
    val source: String = "LRCLIB",
    val fetchedAt: Long = System.currentTimeMillis()
)

@Entity(tableName = "library_source_folders")
data class LibrarySourceFolder(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val folderUri: String,
    val folderName: String,
    val lastScannedAt: Long = 0L
)

@Entity(tableName = "recent_searches")
data class RecentSearch(
    @PrimaryKey val query: String,
    val timestamp: Long = System.currentTimeMillis()
)
