package com.trixxexe.trixxwave.data.db

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "playlists")
data class Playlist(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String = "",
    val description: String = "",
    val isAutoGenerated: Boolean = false,
    val dateAdded: Long = 0
)
